# Generated by Django 3.2.10 on 2022-07-22 13:09

import django.core.validators
from django.db import migrations, models
import interns.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('profile_image', models.FileField(blank=True, max_length=255, null=True, upload_to=interns.models.upload_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'])])),
            ],
        ),
    ]
